# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_dollar_rate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_dollar_rate.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15get_dollar_rate.proto\"\x12\n\x10GetDollarRequest\"\'\n\x11GetDollarResponse\x12\x12\n\nvalue_rate\x18\x01 \x01(\x02\x32K\n\x11GetDollarServices\x12\x36\n\rGetDollarRate\x12\x11.GetDollarRequest\x1a\x12.GetDollarResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETDOLLARREQUEST = _descriptor.Descriptor(
  name='GetDollarRequest',
  full_name='GetDollarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=43,
)


_GETDOLLARRESPONSE = _descriptor.Descriptor(
  name='GetDollarResponse',
  full_name='GetDollarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value_rate', full_name='GetDollarResponse.value_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['GetDollarRequest'] = _GETDOLLARREQUEST
DESCRIPTOR.message_types_by_name['GetDollarResponse'] = _GETDOLLARRESPONSE

GetDollarRequest = _reflection.GeneratedProtocolMessageType('GetDollarRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETDOLLARREQUEST,
  __module__ = 'get_dollar_rate_pb2'
  # @@protoc_insertion_point(class_scope:GetDollarRequest)
  ))
_sym_db.RegisterMessage(GetDollarRequest)

GetDollarResponse = _reflection.GeneratedProtocolMessageType('GetDollarResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETDOLLARRESPONSE,
  __module__ = 'get_dollar_rate_pb2'
  # @@protoc_insertion_point(class_scope:GetDollarResponse)
  ))
_sym_db.RegisterMessage(GetDollarResponse)


# @@protoc_insertion_point(module_scope)
